In [1]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

In [2]:
docs = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다',
       '한번 더 보고 싶네요', '글쎄요', '별로예요', '생각보다 지루하네요', 
        '연기가 어색해요', '재미없어요']

# 긍정 리뷰에는 1을, 부정 리뷰에는 0을 부여
classes = array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [3]:
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고': 13, '싶네요': 14, '글쎄요': 15, '별로예요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}


In [4]:
x = token.texts_to_sequences(docs)
padded_x = pad_sequences(x, 4)
print(f"\n👉 패딩 결과 :\n{padded_x}")


👉 패딩 결과 :
[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


In [5]:
word_size= len(token.word_index) + 1

model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(padded_x, classes, epochs=20)

print("\n👉 Accuracy : %.4f" %(model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 2s 2s/step - loss: 0.6906 - accuracy: 0.6000
Epoch 2/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6879 - accuracy: 0.6000
Epoch 3/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6853 - accuracy: 0.6000
Epoch 4/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6826 - accuracy: 0.7000
Epoch 5/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6799 - accuracy: 0.8000
Epoch 6/20
1/1 [==============================] - 0s 13ms/step - loss: 0.6772 - accuracy: 0.8000
Epoch 7/20
1/1 [==============================] - 0s 13ms/step - loss: 0.6746 - accuracy: 0.9000
Epoch 8/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6720 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 13ms/step - loss: 0.6693 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 13ms/step - loss: 0.6667 - accuracy: 0.9000
Epoch 11/20
1/1 [==============